/**
 * Listado oficial de alimentos certificados libres de gluten en Chile.
 * Fuente: Fundación Convivir (https://fundacionconvivir.cl)
 * Última actualización del PDF: 18-junio-2026
 *
 * El motor nutricional usa este catálogo para:
 *  - Filtrar/sugerir productos seguros a pacientes con intolerancia al gluten
 *  - Componente GuiaCeliacaConvivir muestra el listado al pro y paciente
 *
 * NOTA CLÍNICA: las formulaciones pueden cambiar — el paciente debe verificar
 * SIEMPRE la etiqueta del producto al comprar. Esta lista es referencial.
 */

export interface ItemCeliaco {
  tipo:    string  // ej "Jugo", "Mayonesa"
  producto: string
  empresa: string
  /** true si el item está en "ALIMENTOS QUE NO HAN RENOVADO ANÁLISIS"
   *  (el certificado caducó — verificar con la marca antes de consumir) */
  caducado?: boolean
}

export interface CategoriaCeliaca {
  categoria: string
  emoji:     string
  items:     ItemCeliaco[]
}

export const CATALOGO_CELIACO_CONVIVIR: CategoriaCeliaca[] = [
  {
    categoria: 'Bebidas y jugos',
    emoji:     '🥤',
    items: [
      { tipo: 'Jugo',  producto: "Jugo Naranja 0% 300cc/1.5L/1.75L",          empresa: "Watt's - CCU" },
      { tipo: 'Jugo',  producto: "Jugo Durazno 0% 300cc/1.5L/1.75L",          empresa: "Watt's - CCU" },
      { tipo: 'Jugo',  producto: "Jugo Maracuyá 0% 1.5L",                       empresa: "Watt's - CCU" },
      { tipo: 'Jugo',  producto: "Jugo Tuttifrutilla 0% 300cc/1.5L/1.75L",     empresa: "Watt's - CCU" },
      { tipo: 'Jugo',  producto: "Jugo Piña 0% 1.5L/1.75L",                     empresa: "Watt's - CCU" },
      { tipo: 'Jugo',  producto: "Jugo Tuttiarándano 0% 1.5L",                  empresa: "Watt's - CCU" },
      { tipo: 'Jugo',  producto: "Jugo Mango 0% 1.5L",                          empresa: "Watt's - CCU" },
      { tipo: 'Jugo',  producto: "Jugo Tuttiarándano 1.5L",                     empresa: "Watt's - CCU" },
      { tipo: 'Jugo',  producto: "Jugo Tuttifrutilla 300cc/1.5L/1.75L",         empresa: "Watt's - CCU" },
      { tipo: 'Jugo',  producto: "Jugo Tuttikiwi 1.5L",                          empresa: "Watt's - CCU" },
      { tipo: 'Jugo',  producto: "Jugo Durazno 300cc/1.5L/1.75L",                empresa: "Watt's - CCU" },
      { tipo: 'Jugo',  producto: "Jugo Damasco 300cc/1.5L/1.75L",                empresa: "Watt's - CCU" },
      { tipo: 'Jugo',  producto: "Jugo Naranja 300cc/1.5L/1.75L",                empresa: "Watt's - CCU" },
      { tipo: 'Jugo',  producto: "Jugo Piña 300cc/1.5L/1.75L",                   empresa: "Watt's - CCU" },
      { tipo: 'Jugo',  producto: "Jugo Manzana 300cc/1.5L/1.75L",                empresa: "Watt's - CCU" },
      { tipo: 'Jugo',  producto: "Jugo Naranja Manzana 300cc/1.5L/1.75L",        empresa: "Watt's - CCU" },
      { tipo: 'Jugo',  producto: "Jugo Naranja Plátano 300cc/1.5L/1.75L",        empresa: "Watt's - CCU" },
      { tipo: 'Jugo',  producto: "Frugo Frutilla 2L",                            empresa: "Watt's - CCU" },
      { tipo: 'Jugo',  producto: "Frugo Naranja 2L",                             empresa: "Watt's - CCU" },
      { tipo: 'Jugo',  producto: "Frugo Piña 2L",                                empresa: "Watt's - CCU" },
      { tipo: 'Jugo',  producto: "Jugo Manzana Verde de la Patagonia 1L",        empresa: "PURA FRUTTA (Cencosud)" },
      { tipo: 'Jugo',  producto: "Jugo Blend Detox 1L",                          empresa: "PURA FRUTTA (Cencosud)" },
      { tipo: 'Jugo',  producto: "Jugo Manzana Roja de la Patagonia 1L",         empresa: "PURA FRUTTA (Cencosud)" },
      { tipo: 'Bebida energética', producto: "Rockstar 500ml", empresa: "CCU" },
      { tipo: 'Bebida fantasía', producto: "Kem Piña Zero 600cc",               empresa: "CCU" },
      { tipo: 'Bebida fantasía', producto: "Kem Piña varios formatos",          empresa: "CCU" },
      { tipo: 'Bebida fantasía', producto: "Kem Xtreme Sugar Free 600cc",       empresa: "CCU" },
      { tipo: 'Bebida fantasía', producto: "Kem Xtreme varios formatos",        empresa: "CCU" },
      { tipo: 'Bebida fantasía', producto: "Orange Crush varios formatos",      empresa: "CCU" },
      { tipo: 'Bebida fantasía', producto: "Orange Crush Zero varios formatos", empresa: "CCU" },
      { tipo: 'Bebida fantasía', producto: "Agua Tónica Canada Dry / Zero",     empresa: "CCU" },
      { tipo: 'Bebida fantasía', producto: "Ginger Ale Canada Dry / Zero / Light", empresa: "CCU" },
      { tipo: 'Bebida fantasía', producto: "Limón Soda / Zero varios formatos", empresa: "CCU" },
      { tipo: 'Bebida fantasía', producto: "7Up / Zero varios formatos",        empresa: "CCU" },
      { tipo: 'Bebida fantasía', producto: "Pepsi / Zero varios formatos",      empresa: "CCU" },
      { tipo: 'Bebida fantasía', producto: "Pap / Zero varios formatos",        empresa: "CCU" },
      { tipo: 'Bebida fantasía', producto: "Bilz / Zero varios formatos",       empresa: "CCU" },
      { tipo: 'Refresco té', producto: "Lipton Raspberry 310ml/600ml/1.5L",     empresa: "CCU" },
      { tipo: 'Jugo natural', producto: "Watt's Selección Mango Maracuyá 350cc/1L", empresa: "Watt's - CCU" },
      { tipo: 'Jugo natural', producto: "Watt's Selección Piña Guayaba 350cc/1L",   empresa: "Watt's - CCU" },
      { tipo: 'Jugo natural', producto: "Watt's Selección Papaya 350cc/1L",         empresa: "Watt's - CCU" },
      { tipo: 'Jugo natural', producto: "Watt's Selección Naranja Valencia 350cc/1L", empresa: "Watt's - CCU" },
      { tipo: 'Agua saborizada', producto: "Agua Limón NEXT 500ml/1.5L",        empresa: "Soprole" },
      { tipo: 'Agua saborizada', producto: "Mas Citrus varios formatos",        empresa: "CCU" },
      { tipo: 'Agua saborizada', producto: "H2OH! Limonada / Naranchelo",      empresa: "CCU" },
      { tipo: 'Agua saborizada', producto: "Agua Más Manzana/Granada/Uva/Piña/Pera/Limonada/Mango Maracuyá", empresa: "CCU" },
      { tipo: 'Agua saborizada', producto: "Agua Frambuesa NEXT 500ml/1.5L",   empresa: "Soprole" },
      { tipo: 'Agua sin gas', producto: "Agua Sin Gas NEXT 500ml/1.5L",         empresa: "Soprole" },
      { tipo: 'Bebida analcohólica', producto: "Ginger Beer Spicy PIMENTO 250ml", empresa: "PIMENTO (Cencosud)" },
      { tipo: 'Isotónica', producto: "Gatorade Cool Blue 500cc/750cc/1L",        empresa: "CCU" },
      { tipo: 'Isotónica', producto: "Gatorade Naranja / Naranja Zero",          empresa: "CCU" },
      { tipo: 'Isotónica', producto: "Gatorade Frutas Tropicales / Maracuyá / Limón / Blue Berry Zero", empresa: "CCU" },
    ],
  },
  {
    categoria: 'Aderezos, salsas y aliños',
    emoji: '🥫',
    items: [
      { tipo: 'Mayonesa', producto: "Hellmann's 280/400/430/735/900g",          empresa: "Unilever" },
      { tipo: 'Mayonesa', producto: "Salsa de Ajo Hellmann's 372g",              empresa: "Unilever" },
      { tipo: 'Mayonesa', producto: "Mayonesa casera YBARRA (sin gluten/lactosa) 426g", empresa: "Ybarra (Cencosud)" },
      { tipo: 'Mayonesa', producto: "Mayonesa liviana YBARRA 445g",              empresa: "Ybarra (Cencosud)" },
      { tipo: 'Mayonesa', producto: "Ajonesa Chovi 820ml",                       empresa: "Chovi (Cencosud)" },
      { tipo: 'Mayonesa', producto: "Mayonesa American Dream 394/527/789g",      empresa: "Cuisine&Co (JUMBO)" },
      { tipo: 'Salsa',    producto: "Salsa Vegana Hellmann's 940g",              empresa: "Malloa - Unilever" },
      { tipo: 'Salsa',    producto: "Salsa American Dream Chicken Dipping 488g", empresa: "Cuisine&Co (JUMBO)" },
      { tipo: 'Mostaza',  producto: "Mostaza Sweet & Hot / Horseradish / Dijon American Classic 340g", empresa: "American Classic (Cencosud)" },
      { tipo: 'Mostaza',  producto: "Mostaza Doypack 200g",                      empresa: "PONTEVEDRA (Globe Italia)" },
      { tipo: 'Mostaza',  producto: "American Dream Dijon/Spicy Brown/Stoneground/Miel 340-368g", empresa: "Cuisine&Co (JUMBO)" },
      { tipo: 'Mostaza',  producto: "Yellow Mustard 397g / Honey Mustard 340g",  empresa: "American Classic" },
      { tipo: 'Aceto',    producto: "Aderezo Balsámico Briannas 355ml",          empresa: "Briannas (Cencosud)" },
      { tipo: 'Aceto',    producto: "Aderezo Aceto Balsámico Kühne 500ml",       empresa: "Kühne (Cencosud)" },
      { tipo: 'Salsa tomate', producto: "Bruschetta Tomate Perfect Choice 290g", empresa: "Perfect Choice" },
      { tipo: 'Salsa tomate', producto: "Puré/Pulpa tomate Tetra PONTEVEDRA 205-1000g", empresa: "PONTEVEDRA (Globe Italia)" },
      { tipo: 'Salsa tomate', producto: "Salsa Pronto Pizza PONTEVEDRA 520g",    empresa: "PONTEVEDRA (Globe Italia)" },
      { tipo: 'Salsa tomate', producto: "Salsa Tomate American Dream (Albahaca/Marinara/Carne/Champiñones) 680g", empresa: "Cuisine&Co (JUMBO)" },
      { tipo: 'Ketchup',  producto: "Ketchup JB 100/250g",                       empresa: "Unilever" },
      { tipo: 'Ketchup',  producto: "Hellmann's 500g/1kg",                       empresa: "Unilever/Malloa" },
      { tipo: 'Ketchup',  producto: "Doypack PONTEVEDRA 200g",                    empresa: "PONTEVEDRA (Globe Italia)" },
      { tipo: 'Ketchup',  producto: "Curry Suave Hela 300ml",                    empresa: "Hela (Cencosud)" },
      { tipo: 'Ketchup',  producto: "American Dream Americano 680g/1.07kg",      empresa: "Cuisine&Co (JUMBO)" },
      { tipo: 'Vinagre',  producto: "Vinagre de Manzana 500ml La Fermentista",   empresa: "La Fermentista" },
      { tipo: 'Vinagre',  producto: "Vinagre de Manzana Mi Tierra 500ml",        empresa: "Mi Tierra - NutrisaCorp" },
      { tipo: 'Salsa BBQ', producto: "American Dream BBQ / Hickory / Honey 510g", empresa: "Cuisine&Co (JUMBO)" },
      { tipo: 'Sirope',   producto: "Syrup American Dream / Sin Azúcar 709ml",   empresa: "Cuisine&Co (JUMBO)" },
      { tipo: 'Chucrut',  producto: "Sauerkraut Original/Raíces Nobles/Verdes Vivos/Clásico/Tesoros Marinos 400-680g", empresa: "La Fermentista" },
      { tipo: 'Kimchi',   producto: "Kimchi 400/680/950g",                       empresa: "La Fermentista" },
      { tipo: 'Verdura fermentada', producto: "Betarraga Cruda Beetroots 380/950g", empresa: "La Fermentista" },
    ],
  },
  {
    categoria: 'Harinas, almidones y premezclas',
    emoji: '🌾',
    items: [
      { tipo: 'Almidón', producto: "Almidón de Maíz 1kg",                  empresa: "Allfree" },
      { tipo: 'Almidón', producto: "Almidón de Mandioca 1kg",              empresa: "Allfree" },
      { tipo: 'Harina',  producto: "Harina de Quinoa 500g/2kg",            empresa: "Cosecha Justa" },
      { tipo: 'Harina',  producto: "Harina de Arroz 500g",                 empresa: "Tucapel" },
      { tipo: 'Harina',  producto: "Harina de Arroz Integral 500g/2kg",   empresa: "Cosecha Justa" },
      { tipo: 'Premezcla', producto: "Preparado Panificable No+Gluten",    empresa: "NutrisaCorp" },
      { tipo: 'Premezcla', producto: "Premezcla Masa para Pizza No+Gluten 275g", empresa: "NutrisaCorp" },
      { tipo: 'Premezcla', producto: "Harina Mix B Panadería Schär 1kg",  empresa: "Schär (Globe Italia)" },
      { tipo: 'Harina legumbres', producto: "Harina de Lentejas 500g/2kg", empresa: "Cosecha Justa" },
      { tipo: 'Harina legumbres', producto: "Harina de Garbanzos 500g/2kg", empresa: "Cosecha Justa" },
      { tipo: 'Harina almendra', producto: "Harina Almendras (con/sin piel) El Litral", empresa: "El Litral" },
      { tipo: 'Harina trigo sarraceno', producto: "Harina de Trigo Sarraceno 1kg", empresa: "Allfree" },
      { tipo: 'Harina', producto: "Harina de Quinoa Mi Tierra",            empresa: "Mi Tierra - NutrisaCorp" },
    ],
  },
  {
    categoria: 'Panes, productos horneados y pastelería',
    emoji: '🍞',
    items: [
      { tipo: 'Pan molde',    producto: "Pan Molde Integral No+Gluten 480/600g", empresa: "NutrisaCorp" },
      { tipo: 'Pan molde',    producto: "Pan Molde Blanco No+Gluten 480/600g",   empresa: "NutrisaCorp" },
      { tipo: 'Pan molde',    producto: "Pan Molde Integral 480g",                empresa: "Cuisine&Co (JUMBO)" },
      { tipo: 'Pan hamburguesa', producto: "Pan Hamburguesa Schär 130g",         empresa: "Schär (Globe Italia)" },
      { tipo: 'Pan hallulla', producto: "Hallulla Prehorneado No+Gluten 320g",  empresa: "NutrisaCorp" },
      { tipo: 'Pan completo', producto: "Pan de Completo No+Gluten",             empresa: "NutrisaCorp" },
      { tipo: 'Pan',          producto: "Marraqueta No+Gluten",                   empresa: "NutrisaCorp" },
      { tipo: 'Pan',          producto: "Pan Francés Schär 100g",                  empresa: "Schär (Globe Italia)" },
      { tipo: 'Pan',          producto: "Pan Bisnaguinha Schär 150g",              empresa: "Schär (Globe Italia)" },
      { tipo: 'Pan',          producto: "Pan Manzana y Canela Schär 200g",         empresa: "Schär (Globe Italia)" },
      { tipo: 'Tortilla low carb', producto: "Cetortillas (Flower/Gold/Mediterránea/Tradicional/Cioccolata)", empresa: "Cetortillas" },
      { tipo: 'Tortilla maíz', producto: "Tortilla de Maíz Saniito (Mini/Taquera/Fajita)", empresa: "Grupo Maizal" },
      { tipo: 'Tortilla',     producto: "Tortilla No+Gluten",                      empresa: "NutrisaCorp" },
      { tipo: 'Pan pita',     producto: "Pan Pita No+Gluten",                       empresa: "NutrisaCorp" },
      { tipo: 'Queque',       producto: "Mini Queques Vainilla No+Sellos 5un 50g", empresa: "NutrisaCorp" },
      { tipo: 'Queque',       producto: "Queque Naranja/Chocolate Schär 6un 200g", empresa: "Schär (Globe Italia)" },
      { tipo: 'Merenguito',   producto: "Merenguitos Sin Azúcar Mi Otra Pasión",   empresa: "Mi Otra Pasión" },
      { tipo: 'Cocada',       producto: "Cocadas 100g",                              empresa: "Mi Otra Pasión" },
      { tipo: 'Alfajor',      producto: "Alfajor Relleno Manjar 80g",                empresa: "Mi Otra Pasión" },
      { tipo: 'Barquillo',    producto: "Barquillo Helado Sin Azúcar 30un",         empresa: "Cetortillas" },
    ],
  },
  {
    categoria: 'Galletas',
    emoji: '🍪',
    items: [
      { tipo: 'Galleta maíz', producto: "Cheezy chips snack maíz crema cebolla Be 100g", empresa: "Be" },
      { tipo: 'Galleta maíz', producto: "Galleta maíz sal de mar Be 100g",           empresa: "Be" },
      { tipo: 'Galleta maíz', producto: "Salmas Clásicas 18/80/90/216g",              empresa: "Sanissimo - Grupo Bimbo" },
      { tipo: 'Galleta arroz', producto: "Cerealitas 160g",                            empresa: "Cerealitas - Mondelez" },
      { tipo: 'Galleta arroz', producto: "Galletitas arroz mini con jugo manzana 16g (Líder)", empresa: "Líder - Vida Saludable" },
      { tipo: 'Galleta arroz', producto: "Galleta arroz con sal de mar 110g (Líder)", empresa: "Líder - Vida Saludable" },
      { tipo: 'Galleta arroz', producto: "Galleta arroz endulzada con stevia 110g (Líder)", empresa: "Líder - Vida Saludable" },
      { tipo: 'Galleta arroz', producto: "Galleta Arroz con Chocolate y Naranja 25g", empresa: "Cuisine&Co (JUMBO)" },
      { tipo: 'Galleta arroz', producto: "Galleta Arroz con Chocolate 150g",          empresa: "Cuisine&Co (JUMBO)" },
      { tipo: 'Galleta arroz', producto: "Galleta Arroz con Sal 100g",                empresa: "Cuisine&Co (JUMBO)" },
      { tipo: 'Tostada',  producto: "Tostadas Multigranos con Quinoa Orgran 125g",   empresa: "Orgran (Cencosud)" },
      { tipo: 'Tostada',  producto: "Pan crujiente SPLIIT camote 130g",               empresa: "SPLIT (Cencosud)" },
      { tipo: 'Galleta',  producto: "Snack multigrano Sésamo Sal de Mar Be 100g",    empresa: "Be" },
      { tipo: 'Galleta',  producto: "Snack multigrano Sal de Mar & Pimienta Be 100g", empresa: "Be" },
      { tipo: 'Galleta',  producto: "Galleta Chocolate O's Schär 165g",                empresa: "Schär (Globe Italia)" },
      { tipo: 'Galleta',  producto: "Tostadas de Maíz Orgran 125g",                    empresa: "Orgran (Cencosud)" },
      { tipo: 'Galleta',  producto: "Galletas Mini Chips Chocolate Sin Gluten Gullón 200g", empresa: "Gullón" },
      { tipo: 'Galleta',  producto: "Quest Double Chocolate Chip Cookies caja 12un",  empresa: "Quest" },
      { tipo: 'Galleta',  producto: "Quest Peanut Butter Cookies caja 12un",          empresa: "Quest" },
      { tipo: 'Galleta champaña', producto: "Vicenzovo Sin Gluten 125g",              empresa: "Matilde Vicenzi (Cencosud)" },
    ],
  },
  {
    categoria: 'Cereales y barras',
    emoji: '🥣',
    items: [
      { tipo: 'Cereal',  producto: "Cereal Sabor Cacao Manare 25/250g",         empresa: "Manare" },
      { tipo: 'Cereal',  producto: "Cereal Sabor Dulce Manare 25/250g",          empresa: "Manare" },
      { tipo: 'Cereal',  producto: "Cereal Puff Chocolate Orgran 300g",          empresa: "Orgran (Cencosud)" },
      { tipo: 'Cereal',  producto: "Cereal Sin Gluten Corn Flakes Orgran 300g",  empresa: "Orgran (Cencosud)" },
      { tipo: 'Cereal',  producto: "Cereal Arroz Sabor Berries Orgran 300g",     empresa: "Orgran (Cencosud)" },
      { tipo: 'Barra cereal', producto: "Protein Snack Chocolate & Crispis Your-goal", empresa: "Your-goal" },
      { tipo: 'Barra cereal', producto: "Protein Snack Rich Caramel Your-goal",   empresa: "Your-goal" },
      { tipo: 'Barra proteica', producto: "Quest Bar Chocolate Chip Cookie Dough caja 12un", empresa: "Quest" },
      { tipo: 'Barra proteica', producto: "Quest Hero Bar Blueberry Cobbler caja 12un", empresa: "Quest" },
      { tipo: 'Barra proteica', producto: "Quest Bar Blueberry Muffin caja 12un", empresa: "Quest" },
      { tipo: 'Cereal infantil', producto: "Puffs Frutilla Betarraga/Plátano Zapallo/Manzana Arándano/Pera Espinaca/Cacao 10g/50g", empresa: "Kuna Foods" },
      { tipo: 'Cereal infantil', producto: "Cereal Cacao/Vainilla/Manzana Canela Kuna 280g", empresa: "Kuna Foods" },
      { tipo: 'Quinoa pop', producto: "Quinoa Pop Allfree 180g",                   empresa: "Allfree" },
      { tipo: 'Barra natural', producto: "Barrita natural dátiles con maní Mizos 35g", empresa: "Mizos" },
    ],
  },
  {
    categoria: 'Golosinas (gomitas, chicles, turrón)',
    emoji: '🍬',
    items: [
      { tipo: 'Chicle', producto: "Chicles Frutas Fini 14g/80g", empresa: "Fini" },
      { tipo: 'Gomita', producto: "Gomitas Fini (varios sabores y formatos: Dentaduras, Calavera, Deli Frutas, Frutos Rojos, Postres, Fresas, Huevos Fritos, Ranas, Sandía, Moras, Cereza, Cinema Mix, Corazón Melocotón, Estrellas, Frutillas, Gusanos, Osos, Plátano, Pulpos, Tajadas Sandía, Tiburones, etc.) 15g a 2000g", empresa: "Fini" },
      { tipo: 'Gomita', producto: "Gomitas Violeta / Mix Frutal Gicopa 135g", empresa: "Gicopa (Cencosud)" },
      { tipo: 'Marshmallow', producto: "Marshmallow 10un / Malvas Coco 5un",   empresa: "Mi Otra Pasión" },
      { tipo: 'Marshmallow', producto: "Marshmallow Fini (Mini tubos, Camping, Frutillas, Trenzas, Corazón, Chocolate Dubai, etc.) 80-250g", empresa: "Fini" },
      { tipo: 'Turrón',  producto: "Turrón Jijona Premium 1880 150g",            empresa: "1880 - Pisquera de Chile" },
      { tipo: 'Jamoncito', producto: "Jamoncitos de Chocolate 100g",              empresa: "Mi Otra Pasión" },
    ],
  },
  {
    categoria: 'Chocolates y coberturas',
    emoji: '🍫',
    items: [
      { tipo: 'Chocolate leche', producto: "Chocolate Leche Sin Azúcar Neucober",    empresa: "Industrias Neuchatel" },
      { tipo: 'Chocolate leche', producto: "Chocolate Leche Sucedáneo Neucober",     empresa: "Industrias Neuchatel" },
      { tipo: 'Cobertura', producto: "Chocolate Blanco / Sucedáneo Blanco Neucober", empresa: "Industrias Neuchatel" },
      { tipo: 'Cobertura', producto: "Cobertura para Helados Neucober",                empresa: "Industrias Neuchatel" },
      { tipo: 'Cobertura', producto: "Chocolate de Leche Neucober",                    empresa: "Industrias Neuchatel" },
      { tipo: 'Crema cacao', producto: "Cremonella / Cremonella Sin Azúcar / Cremonel Neucober", empresa: "Industrias Neuchatel" },
      { tipo: 'Chocolate bitter', producto: "Bitter 46% / 60% / 63% / 72% / 85% Cacao Neucober (varios)", empresa: "Industrias Neuchatel" },
      { tipo: 'Chocolate bitter', producto: "Chips Bitter Suave Horneables / Chocolate Bitter Suave", empresa: "Industrias Neuchatel" },
      { tipo: 'Chocolate sucedáneo', producto: "Chocolate Sucedáneo Neucober (varios)", empresa: "Industrias Neuchatel" },
    ],
  },
  {
    categoria: 'Leches',
    emoji: '🥛',
    items: [
      { tipo: 'Leche condensada', producto: "Leche Condensada Nestlé 180g/397g/4.5/6kg", empresa: "Nestlé" },
      { tipo: 'Leche condensada', producto: "Leche Sur 397g",                            empresa: "Nestlé" },
      { tipo: 'Leche condensada', producto: "Condensada Deslactosada 397g",              empresa: "Nestlé" },
      { tipo: 'Leche polvo', producto: "Chocolate en Polvo Dagoat 400g",                 empresa: "Dagoat" },
      { tipo: 'Leche polvo', producto: "Svelty con Colágeno 500g",                       empresa: "Nestlé" },
      { tipo: 'Leche polvo', producto: "Colun Descremada 100/350/800g",                  empresa: "Colun" },
      { tipo: 'Leche polvo', producto: "Colun Entera 120/400/900/1440g/25kg",             empresa: "Colun" },
      { tipo: 'Leche polvo', producto: "Colun Semidescremada 900g",                       empresa: "Colun" },
      { tipo: 'Leche descremada', producto: "Colun Descremada / Sin Lactosa 200ml/1L",   empresa: "Colun" },
      { tipo: 'Leche semidescremada', producto: "Colun Semidescremada 200ml/1L",         empresa: "Colun" },
      { tipo: 'Leche entera', producto: "Colun Entera / Sin Lactosa 200ml/1L",            empresa: "Colun" },
      { tipo: 'Leche con sabor', producto: "Soprole Protein+ Cacao Semi 1L/200ml",       empresa: "Soprole" },
      { tipo: 'Leche con sabor', producto: "Colun Chocolate Semi / Receta Original / Light", empresa: "Colun" },
      { tipo: 'Leche con sabor', producto: "Colun Vainilla / Manjar / Plátano / Frutilla / Caramelo / Capuccino Semi", empresa: "Colun" },
      { tipo: 'Leche con sabor', producto: "Soprole Cookies & Cream 200ml",               empresa: "Soprole" },
      { tipo: 'Leche con sabor', producto: "Colun Chocolate Origen / Desayunow! Manzana / Chocolate", empresa: "Colun" },
      { tipo: 'Leche sin lactosa', producto: "Colun Chocolate Sin Lactosa 200ml/1L",     empresa: "Colun" },
      { tipo: 'Leche cabra', producto: "Leche Cabra Entera/Descremada en Polvo Dagoat 400/900g", empresa: "Dagoat" },
      { tipo: 'Leche A2', producto: "Leche A2 Colun 1L",                                  empresa: "Colun" },
    ],
  },
  {
    categoria: 'Cremas y manjar',
    emoji: '🧈',
    items: [
      { tipo: 'Crema',   producto: "Crema de Leche Light Cuisine&Co 200g",       empresa: "Cuisine&Co (JUMBO)" },
      { tipo: 'Crema',   producto: "Crema Light Colun 200ml",                     empresa: "Colun" },
      { tipo: 'Crema',   producto: "Crema Sin Lactosa Colun 1L",                  empresa: "Colun" },
      { tipo: 'Crema',   producto: "Crema de Leche Soprole 1L",                   empresa: "Soprole" },
      { tipo: 'Crema',   producto: "Crema Regular Colun 200ml/1L",                empresa: "Colun" },
      { tipo: 'Manjar',  producto: "El Manjar Nestlé 200g/500g/1k/800g/6k",        empresa: "Nestlé" },
      { tipo: 'Manjar',  producto: "Chilolac Manjar Bolsa 200g/400g/1k/5k",        empresa: "Chilolac" },
      { tipo: 'Manjar',  producto: "Manjar Cuisine&Co 800g/1kg",                   empresa: "Cuisine&Co (JUMBO)" },
      { tipo: 'Manjar',  producto: "Colun Manjar Rio Bueno 400g/1kg / Sin Azúcar 380g", empresa: "Colun" },
      { tipo: 'Manjar',  producto: "Soprole Manjar Bolsa 200/220/400g / Pote 500g/1kg / Pastelero 5kg / Artesanal", empresa: "Soprole" },
      { tipo: 'Manjar sin lactosa', producto: "El Manjar Deslactosado Nestlé 350g", empresa: "Nestlé" },
      { tipo: 'Dulce leche', producto: "Dulce de Leche Soprole 200g",              empresa: "Soprole" },
    ],
  },
  {
    categoria: 'Mantequillas y margarinas',
    emoji: '🧈',
    items: [
      { tipo: 'Mantequilla', producto: "Colun Mantequilla Los Alerces / con Sal / sin Sal 125/250g", empresa: "Colun" },
      { tipo: 'Mantequilla', producto: "Chilolac Mantequilla con Sal / Ajo y Perejil 125/250g", empresa: "Chilolac" },
      { tipo: 'Mantequilla', producto: "Los Nogales / El Roble / Los Tilos Mantequilla 250g", empresa: "Cial Alimentos / Comercial de Campo" },
      { tipo: 'Mantequilla', producto: "Soprole Mantequilla Untable 200/320g / Quilque 200g", empresa: "Soprole" },
      { tipo: 'Margarina',   producto: "Soprole Margarina con Toques de Mantequilla / NEXT 500g", empresa: "Soprole" },
      { tipo: 'Margarina',   producto: "Doña Juanita 1kg (industrial repostería)",   empresa: "Watt's" },
      { tipo: 'Ghee',        producto: "Mantequilla Clarificada Ghee de Cabra Dagoat 400g", empresa: "Dagoat" },
      { tipo: 'Mantequilla maní', producto: "Mantequilla de Maní NutrisaCorp",         empresa: "NutrisaCorp" },
    ],
  },
  {
    categoria: 'Yogurt y leche cultivada',
    emoji: '🥄',
    items: [
      { tipo: 'Leche cultivada light', producto: "Colun Cultivada Chirimoya/Frambuesa/Frutilla 180ml/1L", empresa: "Colun" },
      { tipo: 'Yogurt batido', producto: "Soprole Yogurt batido Vainilla/Damasco/Piña/Frutilla varios formatos", empresa: "Soprole" },
      { tipo: 'Yogurt batido', producto: "Soprole Zerolacto Frutilla 155g / Batifrut Piña 165g", empresa: "Soprole" },
      { tipo: 'Yogurt batido', producto: "Soprole Protein / Protein+ Trozos Frutos Secos / Kiwi-Plátano-Mango 155g", empresa: "Soprole" },
      { tipo: 'Yogurt batido', producto: "Colun Light Frutilla/Mora/Vainilla/Natural Endulzado Naturalmente 120/900g", empresa: "Colun" },
      { tipo: 'Yogurt batido', producto: "Colun Light Sin Azúcar Frutilla/Chirimoya/Vainilla 120g", empresa: "Colun" },
      { tipo: 'Yogurt batido', producto: "Colun Los Alerces Mora/Frutilla/Damasco/Plátano/Vainilla/Piña/Frambuesa 120g/1kg", empresa: "Colun" },
      { tipo: 'Yogurt batido', producto: "Colun Origen Natural/Vainilla/Frutilla/Chirimoya 120g", empresa: "Colun" },
      { tipo: 'Yogurt batido', producto: "Colun Batido Frutilla/Frambuesa/Cereza/Mora/Damasco/Piña/Plátano/Vainilla 125g/1kg", empresa: "Colun" },
      { tipo: 'Yogurt batido', producto: "Nestlé Chamyto Sin Azúcar Damasco/Frutilla/Plátano/Vainilla 115g", empresa: "Nestlé" },
      { tipo: 'Yogurt batido', producto: "Nestlé Chamyto Frambuesa/Frutilla/Manzana/Tutifrutti 80ml", empresa: "Nestlé" },
      { tipo: 'Yogurt batido', producto: "Nestlé Goodness Frutilla/Natural/Vainilla/Mix Berries/Mango/Manzana Ciruela/Plátano Frutilla 140g", empresa: "Nestlé" },
      { tipo: 'Yogurt batido', producto: "Nestlé Goodness Protein Chirimoya/Frutilla/Natural 140g", empresa: "Nestlé" },
      { tipo: 'Yogurt natural', producto: "Chilolac Pote 200g / Bolsa 1L",        empresa: "Chilolac" },
      { tipo: 'Yogurt natural', producto: "Yogurt Griego Natural Nestlé 120g",   empresa: "Nestlé" },
      { tipo: 'Yogurt sin lactosa', producto: "Colun Light Sin Lactosa (Natural/Chirimoya/Frutilla/Vainilla/Damasco/Mora) 120/900g", empresa: "Colun" },
      { tipo: 'Yogurt sin lactosa', producto: "Colun Batido Sin Lactosa (Mora/Frutilla/Damasco/Vainilla) 125g", empresa: "Colun" },
      { tipo: 'Yogurt bebible', producto: "Colun Protein Plus! Vainilla/Frutilla/Frutilla Plátano 150g", empresa: "Colun" },
      { tipo: 'Yogurt bebible', producto: "Colun Protein Plus! Sin Azúcar Frutilla/Chirimoya/Natural 150g", empresa: "Colun" },
      { tipo: 'Kefir', producto: "Colun Kefir Frambuesa/Piña/Naranja/Natural/Frutilla 120g", empresa: "Colun" },
      { tipo: 'Yogurt vegano', producto: "QUOKKA Coco Vainilla / Mango Maracuyá / Frutilla Limón 150g", empresa: "Quokka Foods" },
    ],
  },
  {
    categoria: 'Quesos',
    emoji: '🧀',
    items: [
      { tipo: 'Quesillo', producto: "Quesillo Fundo Santa Ana de Huingan 500g",   empresa: "Santa Ana de Huingan" },
      { tipo: 'Quesillo', producto: "Soprole Quesillo Zerolacto Sin Lactosa 300g", empresa: "Soprole" },
      { tipo: 'Quesillo', producto: "Colun Quesillo 350g",                          empresa: "Colun" },
      { tipo: 'Queso Gauda', producto: "Gouda Laminado Santa Isabel 150/250/500g", empresa: "Santa Isabel (JUMBO)" },
      { tipo: 'Queso Gauda', producto: "Chilolac Gauda Pieza/Medio/Barra/Laminado/Granulado varios",  empresa: "Chilolac" },
      { tipo: 'Queso Gauda', producto: "Gauda Sin Lactosa 200g",                    empresa: "Cuisine&Co (JUMBO)" },
      { tipo: 'Queso Gauda', producto: "Colun Gouda 150/250/500g/1kg",              empresa: "Colun" },
      { tipo: 'Queso Gauda', producto: "Soprole Gauda Hebras 400g / Laminado 150-3.4kg", empresa: "Soprole" },
      { tipo: 'Queso Gauda', producto: "Los Nogales Gauda Laminado 250g/1kg",       empresa: "Cial Alimentos" },
      { tipo: 'Queso Chanco', producto: "Queso Maduro Santa Ana de Huingan 1.5/3.1/10kg", empresa: "Santa Ana de Huingan" },
      { tipo: 'Queso Chanco', producto: "Chilolac Chanco Pieza/Medio/Barra/Trozo/Laminado varios formatos", empresa: "Chilolac" },
      { tipo: 'Queso Chanco', producto: "El Roble Chanco Trozado 250g/400g/1kg",    empresa: "El Roble" },
      { tipo: 'Queso Mantecoso', producto: "Las Águilas Mantecoso/Granulado (Kosher) 30g-10.5k", empresa: "Agrícola Las Águilas" },
      { tipo: 'Queso Mantecoso', producto: "Soprole Quilque Mantecoso Laminado 150-3.4kg", empresa: "Soprole" },
      { tipo: 'Queso Mantecoso', producto: "La Rotunda Mantecoso Laminado/Trozo/Pieza/Granulado", empresa: "La Rotunda" },
      { tipo: 'Queso Mantecoso', producto: "Los Tilos Mantecoso 250/400/450g",      empresa: "Comercial de Campo" },
      { tipo: 'Queso Mantecoso', producto: "Chilolac Mantecoso Pieza/Barra/Trozo/Mini varios formatos", empresa: "Chilolac" },
      { tipo: 'Queso Laminado', producto: "El Roble Laminado 150/250/500g/2kg",     empresa: "El Roble" },
      { tipo: 'Queso Laminado', producto: "Colun Rio Bueno Laminado 150/250/420/500g", empresa: "Colun" },
      { tipo: 'Queso Parmesano', producto: "Los Tilos Parmesano 145g",              empresa: "Los Tilos" },
      { tipo: 'Queso Parmesano', producto: "Cuisine&Co Rallado 80g / Soprole 40/80g", empresa: "Cuisine&Co/Soprole" },
      { tipo: 'Queso Chacra', producto: "El Roble Chacra 450g / Sin Lactosa 350g",  empresa: "El Roble" },
      { tipo: 'Queso Chacra', producto: "Colun Chacra Rio Bueno 400g",              empresa: "Colun" },
      { tipo: 'Queso Fresco', producto: "Las Águilas Fresco Kosher / Sin Lactosa / 280-1kg", empresa: "Las Águilas" },
      { tipo: 'Queso Fresco', producto: "Los Tilos Fresco / Light Sin Lactosa 230-400g", empresa: "Los Tilos" },
      { tipo: 'Queso Fresco', producto: "Colun Fresco 450g / Light Sin Lactosa 400g", empresa: "Colun" },
      { tipo: 'Queso Crema', producto: "El Roble Crema de Queso Natural 190g",      empresa: "El Roble" },
      { tipo: 'Queso Crema', producto: "Chilolac Queso Crema Natural / Merkén 100/200g", empresa: "Chilolac" },
      { tipo: 'Queso Crema', producto: "Colun Crema Untable Tomate Orégano 100g",    empresa: "Colun" },
      { tipo: 'Queso Crema', producto: "Soprole Crema Natural / Tomate Albahaca 100/200g", empresa: "Soprole" },
      { tipo: 'Queso Crema', producto: "Polenghi Cream Cheese (food service) 3.6/1.5kg", empresa: "Santa Rosa" },
      { tipo: 'Queso Crema', producto: "Philadelphia regular 150g",                  empresa: "Kraft Mondelez" },
      { tipo: 'Queso Cabra', producto: "Los Tilos Cabra Oliva Orégano / Natural 200g", empresa: "Los Tilos" },
      { tipo: 'Queso Cabra', producto: "El Roble Cabra 325g",                          empresa: "El Roble" },
      { tipo: 'Queso Brie',  producto: "Los Tilos Brie 125/140g / Colun Brie 125g",   empresa: "Los Tilos/Colun" },
      { tipo: 'Queso Camembert', producto: "Colun Camembert 125g",                    empresa: "Colun" },
      { tipo: 'Mozzarella',  producto: "Dibufala Mozzarella Ciliegine/Burrata/Ovoline/Capreese 125-250g", empresa: "Dibufala (Globe Italia)" },
      { tipo: 'Queso Azul',  producto: "Colun Azul 100g",                              empresa: "Colun" },
      { tipo: 'Queso Ahumado', producto: "El Roble Ahumado 140g / Los Tilos Fundido Ahumado 150-250g", empresa: "El Roble/Los Tilos" },
      { tipo: 'Queso Light', producto: "Colun Light Probióticos 500g",                empresa: "Colun" },
      { tipo: 'Queso Gruyere', producto: "Los Tilos Gruyere 240g",                    empresa: "Los Tilos" },
      { tipo: 'Ricotta',     producto: "Ricotta Leche de Búfala Dibufala 300g",       empresa: "Dibufala (Globe Italia)" },
      { tipo: 'Reggianito',  producto: "Colun Reggianito Rallado 40/80g/2kg / Trozo 200g", empresa: "Colun" },
    ],
  },
  {
    categoria: 'Bebidas vegetales',
    emoji: '🌱',
    items: [
      { tipo: 'Bebida coco',    producto: "Bebida de Coco Sin Azúcar / Normal 1L Cuisine&Co", empresa: "Cuisine&Co (JUMBO)" },
      { tipo: 'Bebida coco',    producto: "Alimento de Coco SAMUI 400ml",            empresa: "Samui (Cencosud)" },
      { tipo: 'Bebida almendra', producto: "Bebida Almendra Vainilla 1L Cuisine&Co", empresa: "Cuisine&Co (JUMBO)" },
      { tipo: 'Bebida arroz',   producto: "Bebida Arroz Original / Chocolate Tucapel 1L", empresa: "Tucapel" },
      { tipo: 'Crema vegetal',  producto: "Crema de Coco SAMUI",                     empresa: "Samui (Cencosud)" },
      { tipo: 'Bebida kefir',   producto: "Bebida Fermentada Kéfir Ginger 330ml",    empresa: "La Fermentista" },
    ],
  },
  {
    categoria: 'Pastas y fideos',
    emoji: '🍝',
    items: [
      { tipo: 'Pasta', producto: "Mostaccholi No+Gluten",                            empresa: "NutrisaCorp" },
      { tipo: 'Pasta', producto: "Fusilli Schär 250g",                               empresa: "Schär (Globe Italia)" },
      { tipo: 'Fideos arroz', producto: "Pasta Rigatti / Spaguetti de Arroz y Huevo Tucapel 250g", empresa: "Tucapel" },
      { tipo: 'Fideos legumbres', producto: "Pasta Penne Garbanzos/Lentejas/Arvejas Cosecha Justa 227g/1kg", empresa: "Cosecha Justa" },
      { tipo: 'Fideos legumbres', producto: "Pasta Fusilli Lenteja/Arvejas/Garbanzos Cosecha Justa 227g/1kg", empresa: "Cosecha Justa" },
      { tipo: 'Fideos arroz', producto: "Pastas Arroz Trattoria 250g (Carozzi)",     empresa: "Carozzi" },
      { tipo: 'Fideos arroz', producto: "Pasta Spaghetti / Fusilli Vivo 250/400g (Carozzi)", empresa: "Carozzi" },
      { tipo: 'Pasta', producto: "Spaghetti No+Gluten",                              empresa: "NutrisaCorp" },
      { tipo: 'Gnocchi', producto: "Gnocchi Schär 300g",                              empresa: "Schär (Globe Italia)" },
    ],
  },
  {
    categoria: 'Frutos secos y deshidratados',
    emoji: '🥜',
    items: [
      { tipo: 'Almendras', producto: "Almendras Tostadas Con/Sin Piel / Laminadas / Naturales El Litral", empresa: "El Litral" },
      { tipo: 'Maní',      producto: "Maní sin piel frito salado / tostado Mani King 500g", empresa: "Mani King (Cencosud)" },
    ],
  },
  {
    categoria: 'Mermeladas y miel',
    emoji: '🍯',
    items: [
      { tipo: 'Miel ulmo', producto: "Miel Cruda de Ulmo La Fermentista 500g/1kg",   empresa: "La Fermentista" },
    ],
  },
  {
    categoria: 'Cóctel y snacks',
    emoji: '🥨',
    items: [
      { tipo: 'Tortilla maíz', producto: "Topitos de Maíz tipo Nacho Saniito 30/80g", empresa: "Grupo Maizal" },
      { tipo: 'Chips veggie', producto: "Veggie Tropical / Mix Andino Inka Chips 125-150g", empresa: "Inka Crops" },
      { tipo: 'Chips papa', producto: "Flip Orizon (Sal Mar, Ajo Albahaca, Camote Betarraga, Merkén, BBQ, Ciboulette, Nativas) 30/140g", empresa: "Flip - Orizon" },
      { tipo: 'Palomitas', producto: "Maíz Gigante Salado Inka Corn 100g",            empresa: "Inka Crops" },
      { tipo: 'Crackers',  producto: "Saltí Schär 175g",                                empresa: "Schär (Globe Italia)" },
      { tipo: 'Snack',     producto: "Bombas Kuna (maní / mediterráneas / queso crema-ciboulette) 20g", empresa: "Kuna Foods" },
      { tipo: 'Papas fritas', producto: "Curvies Original Schär 170g",                  empresa: "Schär (Globe Italia)" },
      { tipo: 'Papas fritas', producto: "Inka Chips Saladas / Cebolla Caramelizada BBQ / Jalapeño 150g", empresa: "Inka Crops" },
      { tipo: 'Papas fritas', producto: "Tottus Orégano-Oliva / Artesanales Nativas 142g (Inka Crops)", empresa: "Tottus" },
      { tipo: 'Chips maíz', producto: "Chips Saniito Natural 30/80g",                  empresa: "Grupo Maizal" },
      { tipo: 'Chips maíz', producto: "Nachos Albahaca Tomate / Maíz Cancha Serrana / Maíz Gigante Picante Inka Corn", empresa: "Sanissimo/Inka Crops" },
      { tipo: 'Chips maíz', producto: "Salmas Chía Linaza / Clásicas 108/160g",         empresa: "Sanissimo - Grupo Bimbo" },
      { tipo: 'Gomitas fruta', producto: "Gumis Berries / Durazno / Piña Kuna 16g",      empresa: "Kuna Foods" },
      { tipo: 'Plátano frito', producto: "Inka Chips Picante / Salado / Maduro 100g",    empresa: "Inka Crops" },
      { tipo: 'Yuca/Camote/Habas', producto: "Inka Chips Yuca Salada / Camote con Sal / Habas Fritas 130-150g", empresa: "Inka Crops" },
      { tipo: 'Snack carne', producto: "Mini Snack Peperoni / Salamini Receta del Abuelo", empresa: "PF Alimentos" },
      { tipo: 'Snack carne', producto: "Snackin Beef Jerky 20g",                          empresa: "La Preferida" },
    ],
  },
  {
    categoria: 'Postres y compotas',
    emoji: '🍮',
    items: [
      { tipo: 'Flan',     producto: "Soprole Zerolacto Caramelo / Vainilla 120g",     empresa: "Soprole" },
      { tipo: 'Flan',     producto: "Colun Chocolate / Vainilla / Manjar 100g",        empresa: "Colun" },
      { tipo: 'Flan',     producto: "Carmencita Flan clásico 20g",                     empresa: "Carmencita" },
      { tipo: 'Postre crema', producto: "Colun Postre del Sur Manjar/Chocolate/Chocolate Blanco/Moka/Chocolate Menta 110g", empresa: "Colun" },
      { tipo: 'Postre crema', producto: "Colun Cremisimo Lúcuma/Vainilla/Chocolate Almendra 100g", empresa: "Colun" },
      { tipo: 'Postre crema', producto: "Carmencita Crema Catalana 80g",                empresa: "Carmencita" },
      { tipo: 'Jalea',    producto: "Soprole Splash Tutti Pop / Funny Apple 110g",      empresa: "Soprole" },
      { tipo: 'Jalea',    producto: "Colun Limón/Naranja/Guinda/Frambuesa 100g",         empresa: "Colun" },
      { tipo: 'Mousse',   producto: "Chandelle Suspiro Maracuyá 130g / Sin Lactosa Chocolate 120g", empresa: "Nestlé" },
      { tipo: 'Mousse',   producto: "Chandelle Crema Irlandesa / Piña Colada 120g",    empresa: "Nestlé" },
      { tipo: 'Natilla',  producto: "Natillas en Polvo Caseras Carmencita 80g",         empresa: "Carmencita" },
      { tipo: 'Alimento veggie', producto: "Veggie de Coco / con Berries / con Frutilla Nestlé 115g", empresa: "Nestlé" },
    ],
  },
  {
    categoria: 'Helados',
    emoji: '🍦',
    items: [
      { tipo: 'Helado',  producto: "Palettas Peanut Caramel / Chocolate Almendras / Dulce de Leche", empresa: "Palettas - Emporio La Rosa" },
      { tipo: 'Helado',  producto: "Emporio La Rosa Frutilla Sin Azúcar / Chocolate Araucano 550g", empresa: "Emporio La Rosa" },
      { tipo: 'Helado',  producto: "Savory Frambuesa 0%/Pasas al Ron/Piña Colada/Piña/Vainilla/Centella Manzana Limón", empresa: "Nestlé" },
      { tipo: 'Helado',  producto: "Chamonix Tres Leches Chocolate / Piña / Trisabor 2.5L", empresa: "Nestlé" },
      { tipo: 'Helado',  producto: "Chomp Sahne Nuss / Pura Frutta Frambuesa/Mango 225ml", empresa: "Nestlé" },
      { tipo: 'Helado',  producto: "Savory 3 Leches / Chirimoya Alegre / Chocolate Suizo / Frutos Bosque 1L", empresa: "Nestlé" },
      { tipo: 'Helado agua', producto: "Multi Palettas 12un 504g",                       empresa: "Palettas - Emporio La Rosa" },
      { tipo: 'Bombón',  producto: "Emporio La Rosa Bombón Frambuesa / Vainilla Crocante 182g", empresa: "Emporio La Rosa" },
      { tipo: 'Helado fruta', producto: "Palettas Frutos del Bosque / Limón Menta Jengibre 5un 290g", empresa: "Palettas - Emporio La Rosa" },
    ],
  },
  {
    categoria: 'Conservas',
    emoji: '🥫',
    items: [
      { tipo: 'Atún',     producto: "Caballa filete aceite maravilla 125g",            empresa: "Fisherman - Orizon" },
      { tipo: 'Alcachofa', producto: "Don Giuseppe Corazones 400g / Fondos 800g",      empresa: "Don Giuseppe" },
      { tipo: 'Espárragos', producto: "Don Giuseppe Verdes Enteros 425g",              empresa: "Don Giuseppe" },
      { tipo: 'Pimiento',  producto: "Don Giuseppe Pimiento Piquillo 400g",            empresa: "Don Giuseppe" },
      { tipo: 'Palmitos',  producto: "Don Giuseppe Corazones / Medallones 400g",       empresa: "Don Giuseppe" },
      { tipo: 'Jurel',     producto: "San José / Fisherman Jurel lomo/lomito/filete (natural/aceite oliva/maravilla) 125-425g", empresa: "Orizon" },
      { tipo: 'Champiñones', producto: "Don Giuseppe Enteros / Laminados 400g",        empresa: "Don Giuseppe" },
    ],
  },
  {
    categoria: 'Cecinas (jamones, salames, chorizos)',
    emoji: '🥩',
    items: [
      { tipo: 'Salchichón', producto: "Salchichón Cervecero Receta del Abuelo",        empresa: "PF Alimentos" },
      { tipo: 'Pechuga pavo', producto: "La Preferida Pechuga Pavo Acaramelado / Cocida 125g", empresa: "La Preferida" },
      { tipo: 'Salchicha',  producto: "Salchicha de Pavo / con Pavo / La Española vienesas", empresa: "PF Alimentos" },
      { tipo: 'Salame',     producto: "Snackin Salame 50g / Salame Ahumado / Artesanal / Tradicional / Italiano Laminado", empresa: "PF Alimentos / La Preferida / San Jorge" },
      { tipo: 'Salame italiano', producto: "Simonini Spianata Romana / Contadino / Guanciale / Piccante / Spianata Milano (importado)", empresa: "Simonini (Globe Italia)" },
      { tipo: 'Chorizo',    producto: "Receta del Abuelo Chorizo Parrillero (Angus/Tradicional/Ahumado/de Campo/Sarta)", empresa: "PF Alimentos" },
      { tipo: 'Longaniza',  producto: "Receta del Abuelo Longaniza (Angus/Tradicional/Sureña/Ahumada/Parrillera/al Merkén)", empresa: "PF Alimentos" },
      { tipo: 'Burifarra',  producto: "San Manuelina Burifarra 250g / Longaniza Tradicional 500g / Longanicilla 250g", empresa: "San Manuelina" },
      { tipo: 'Jamón pierna', producto: "PF Jamón Pierna (Acaramelado/Artesanal/Receta del Abuelo/Ahumado/Sandwich)", empresa: "PF Alimentos" },
      { tipo: 'Jamón pierna', producto: "La Preferida Pluma 125g / Winter Jamón Pierna",   empresa: "La Preferida / Winter" },
      { tipo: 'Paté ternera', producto: "Paté Ternera San Jorge 125g",                       empresa: "San Jorge" },
      { tipo: 'Tocino',     producto: "PF Tocino Ahumado / La Preferida Parrillero/Cortado 180g", empresa: "PF Alimentos / La Preferida" },
      { tipo: 'Jamón pavo', producto: "La Preferida Pechuga Ahumada Pavo 125g / PF Jamón Pavo / San Jorge Ahumado 500g", empresa: "La Preferida / PF / San Jorge" },
      { tipo: 'Jamón artesanal', producto: "San Jorge Artesanal 200g",                       empresa: "San Jorge" },
      { tipo: 'Jamón serrano', producto: "La Preferida 80g / PF Receta del Abuelo / Simonini Prosciutto Crudo Delizia 100-400g", empresa: "La Preferida / PF / Simonini" },
      { tipo: 'Mortadela',  producto: "PF Mortadela (Fina/Alemana/Jamonada/Receta del Abuelo)", empresa: "PF Alimentos" },
      { tipo: 'Mortadela',  producto: "Winter Salchichón Cerveza / San Jorge Jamonada/Lisa 250g/400g", empresa: "Winter / San Jorge" },
      { tipo: 'Mortadela italiana', producto: "Simonini Bologna con Pistachos 200g / Modenella 80g", empresa: "Simonini (Globe Italia)" },
      { tipo: 'Paté',       producto: "PF Paté de cerdo / pavo / Pasta Sabor Jamón",         empresa: "PF Alimentos" },
      { tipo: 'Arrollado',  producto: "San Jorge Arrollado Lomo/Huaso con Ají 150g / PF Huaso/Artesanal", empresa: "San Jorge / PF Alimentos" },
      { tipo: 'Jamón',      producto: "PF Fiambre Sándwich / Pechuga Pollo Cocida / Glacé / Ahumado / Artesanal", empresa: "PF Alimentos" },
      { tipo: 'Jamón',      producto: "Winter Acaramelado tradicional / 200g laminado / La Preferida Centenario", empresa: "Winter / La Preferida" },
      { tipo: 'Jamón italiano', producto: "Simonini Prosciutto Superiore Bellagio 100g / Copa Stagionata 2.5kg", empresa: "Simonini (Globe Italia)" },
      { tipo: 'Jamonada',   producto: "PF Pavo / Pollo Receta del Abuelo / Cocida",          empresa: "PF Alimentos" },
      { tipo: 'Prieta',     producto: "PF Prieta a la Chilena / Receta del Abuelo / San Manuelina 500g", empresa: "PF / San Manuelina" },
      { tipo: 'Pasta untable', producto: "Receta del Abuelo Pasta Jamón Serrano / Ave Mayo / Salame / Pollo Finas Hierbas", empresa: "PF Alimentos" },
      { tipo: 'Vienesa',    producto: "San Jorge Vienesa 1kg",                                empresa: "San Jorge" },
      { tipo: 'Salchicha',  producto: "Receta del Abuelo Premium / Sureña / Tradicional / Pavo / Bronto 475g / La Preferida 750g", empresa: "PF / San Jorge / La Preferida" },
      { tipo: 'Peperoni',   producto: "Peperoni PF",                                            empresa: "PF Alimentos" },
    ],
  },
  {
    categoria: 'Carnes (pollo, pavo)',
    emoji: '🍗',
    items: [
      { tipo: 'Pollo',       producto: "Pollo Entero Sin/Con Menudencias Sin Marinar Canto del Gallo", empresa: "Ariztía" },
      { tipo: 'Filetillo',   producto: "Filetillo Pollo Canto del Gallo 580g / Pechuga 480/830g",    empresa: "Ariztía" },
      { tipo: 'Filetillo',   producto: "Filetillo Pollo Sin Marinar 800g",                            empresa: "Cuisine&Co (JUMBO)" },
      { tipo: 'Pechuga pollo', producto: "Ariztía Pechuga Deshuesada/Entera (refrigerada/marinada/sin marinar)", empresa: "Ariztía" },
      { tipo: 'Pechuga pollo', producto: "Cuisine&Co Pechuga Sin Marinar 800g",                       empresa: "Cuisine&Co (JUMBO)" },
      { tipo: 'Pollo',         producto: "Adoro Pollo Línea Natural / Adobado / Tender / Marinado",  empresa: "Adoro" },
      { tipo: 'Trutro pollo',  producto: "Ariztía Trutro Corto/Largo/Combinado (sin marinar / marinado) varios formatos", empresa: "Ariztía" },
      { tipo: 'Trutro pollo',  producto: "Cuisine&Co Trutro Corto/Largo 1kg",                          empresa: "Cuisine&Co (JUMBO)" },
      { tipo: 'Menudencias',   producto: "Ariztía Panita 600g / Contre 480g",                          empresa: "Ariztía" },
      { tipo: 'Pavo',          producto: "Ariztía Molida de Pavo 400g / Pavo Entero Marinado / Pechuga Deshuesada", empresa: "Ariztía" },
      { tipo: 'Pavo',          producto: "Bistec Pechuga Pavo 450g Ariztía Light / Filete 800g Cuisine&Co", empresa: "Ariztía / Cuisine&Co" },
      { tipo: 'Carne molida',  producto: "Ariztía Carne Molida Pechuga Pollo 400g / San Jorge 250g",   empresa: "Ariztía / San Jorge" },
    ],
  },
  {
    categoria: 'Hamburguesas',
    emoji: '🍔',
    items: [
      { tipo: 'Hamburguesa', producto: "La Preferida Angus 100/185g / San Jorge 90g / Bronto 185g / Winter 50g", empresa: "La Preferida / San Jorge / Winter" },
    ],
  },
  {
    categoria: 'Comida preparada',
    emoji: '🍲',
    items: [
      { tipo: 'Plato preparado', producto: "Sabores de la Pao (Garbanzos / Porotos / Porotos Granados / Carbonada / Carne mechada / Charquicán / Lentejas al curry / Pollo al cognac / Tomaticán / Cremas) frasco vidrio 400g", empresa: "Sabores de la Pao" },
      { tipo: 'Sándwich', producto: "Sándwich Jamón Queso Gluten Free Starbucks",          empresa: "Cetortillas" },
    ],
  },
  {
    categoria: 'Comida para bebés',
    emoji: '🍼',
    items: [
      { tipo: 'Colado fruta', producto: "Compota NaturNes orgánico manzana sin azúcar 113g", empresa: "Nestlé" },
    ],
  },
  {
    categoria: 'Suplementos y fórmulas',
    emoji: '💊',
    items: [
      { tipo: 'Magnesio', producto: "Cloruro Magnesio Dulzura Natural 125g / Citrato Magnesio 90g", empresa: "Dulzura Natural" },
      { tipo: 'Suplemento', producto: "ITF Labomed (Ergosel D / Fersitol D / Naticare LAT/PRE/SUPRA / BILDAX / Z-ZINCOVIT PLUS / BIOSUL)", empresa: "ITF Labomed" },
      { tipo: 'Vitaminas', producto: "Solgar (Cranberry / Calcium Citrate D3 / Triple Strength Omega 3 / Essential Amino / L-Arginina / Vit C / Vit D3 / Vit E / Magnesium / Calcio Magnesio Zinc)", empresa: "Solgar" },
      { tipo: 'Vitaminas', producto: "German Energy Bio Plus (Vit C / Biotina / Multivitamínico / B-Complex / Magnesio+B / Magnesio+Zinc / Mg+VitB)", empresa: "German Energy - Bio Plus" },
      { tipo: 'Suplemento', producto: "Dulzura Natural (Probióticos 20B/50B / Vit B12 / Hierro / Vit C / Ácido fólico / Biotina / Calcio / Omega 3 vegano / Vit A/B3/B6/D2/D3/E/K2 / Zinc / Potasio / Levadura Nutricional)", empresa: "Dulzura Natural" },
      { tipo: 'Suplemento nutricional', producto: "Laboratorio Boston Nat100 (Balance Plus / Diabético / Pediátrico / Triple Fibra / Módulo Calórico/Espesante/Proteico)", empresa: "Lab. Boston" },
      { tipo: 'Suplemento nutricional', producto: "Abbott Ensure (Advance varios sabores / Clinical / Compact / NG / Plus) y Glucerna / Pediasure / Similac / Nepro / Lactosa Jevity", empresa: "Abbott Nutrition" },
      { tipo: 'Batido proteínas', producto: "Quest Protein Shake (Chocolate / Salted Caramel / Vainilla) 325ml", empresa: "Quest" },
      { tipo: 'Fitoesteroles', producto: "Cardiosmile Nutrartis 30un 315ml / 60un 630ml",   empresa: "Nutrartis" },
      { tipo: 'Vitaminas proteína', producto: "Sportlab Vegan Matrix Chocolate / Vainilla 2 lb", empresa: "Sportlab" },
      { tipo: 'Vit D3', producto: "Sundown Naturals Vit D3 10 mcg 400 IU 100 softgels",     empresa: "Sundown Naturals" },
    ],
  },
  {
    categoria: 'Endulzantes y azúcares',
    emoji: '🍚',
    items: [
      { tipo: 'Azúcar', producto: "Azúcar Rubia NutrisaCorp 750g / Allfree 1kg",            empresa: "NutrisaCorp / Allfree" },
      { tipo: 'Estevia', producto: "Stevia Pura Dulzura Natural sobre/tubo 10g",            empresa: "Dulzura Natural" },
      { tipo: 'Panela', producto: "Chancaca Deliciosa 400g",                                empresa: "Deliciosa" },
    ],
  },
  {
    categoria: 'Cereales y legumbres (grano)',
    emoji: '🍚',
    items: [
      { tipo: 'Quinoa',     producto: "Cosecha Justa Quinoa 600g/2kg",                       empresa: "Cosecha Justa" },
      { tipo: 'Arroz',      producto: "Cosecha Justa Blanco / Integral 600g/2kg",            empresa: "Cosecha Justa" },
      { tipo: 'Arroz',      producto: "Tucapel Gran Selección G1/G2 / Banquete Premium varios formatos", empresa: "Tucapel" },
      { tipo: 'Garbanzos',  producto: "Cosecha Justa 600g/2kg / Don Giuseppe 340g",          empresa: "Cosecha Justa / Don Giuseppe" },
      { tipo: 'Lentejas',   producto: "Cosecha Justa 600g/2kg / Don Giuseppe 340g",          empresa: "Cosecha Justa / Don Giuseppe" },
      { tipo: 'Arvejas',    producto: "Don Giuseppe Arvejas verdes partidas 340g",           empresa: "Don Giuseppe" },
    ],
  },
  {
    categoria: 'Ingredientes para repostería',
    emoji: '🥄',
    items: [
      { tipo: 'Goma',     producto: "Goma Xanthan Allfree 100g / Goma Guar 100g",            empresa: "Allfree" },
      { tipo: 'Levadura', producto: "Levadura Nutricional en Polvo Dulzura Natural 100g",    empresa: "Dulzura Natural" },
      { tipo: 'Polvo hornear', producto: "Polvo de Hornear Allfree 100g",                     empresa: "Allfree" },
      { tipo: 'Esencia vainilla', producto: "Esencia Vainilla Allfree 60/120ml",              empresa: "Allfree" },
    ],
  },
  {
    categoria: 'Condimentos, especias y aliños',
    emoji: '🌶️',
    items: [
      { tipo: 'Caldo',     producto: "Gallina Blanca Caldo Casero (Carne/Gallina/Verduras/Paella) 1L", empresa: "Gallina Blanca (Globe Italia)" },
      { tipo: 'Sazonador', producto: "Carmencita Paella Kit Marisco / Sazonador Verduras/Paella/Barbacoa/Pescado/Pollo molinillo", empresa: "Carmencita (Cencosud)" },
      { tipo: 'Pimienta',  producto: "Carmencita Pimienta Negra Molida 52g",                  empresa: "Carmencita" },
      { tipo: 'Cebolla',   producto: "Carmencita Cebolla en Polvo 48g",                       empresa: "Carmencita" },
      { tipo: 'Pimentón',  producto: "Carmencita Pimentón Ahumado / Picante / Dulce 75g",     empresa: "Carmencita" },
      { tipo: 'Cúrcuma',   producto: "Carmencita Cúrcuma Molida 31/48g",                       empresa: "Carmencita" },
      { tipo: 'Sal condimentada', producto: "Carmencita Sal Picante 320g / Sal+Pimienta 225g / Marina Mediterránea Azafrán 360g", empresa: "Carmencita" },
      { tipo: 'Ajo polvo', producto: "Carmencita Ajo en Polvo Basic 40g",                      empresa: "Carmencita" },
      { tipo: 'Aderezo',   producto: "Kühne Aderezo Hierbas 500ml / American Dream Mostaza-Miel / Ranch", empresa: "Kühne / Cuisine&Co" },
      { tipo: 'Condimento', producto: "Carmencita Condimento Paellero 20g",                    empresa: "Carmencita" },
      { tipo: 'Salsa ajo', producto: "Hellmann's 950g / Chovi Allioli 250ml",                  empresa: "Unilever / Chovi" },
    ],
  },
  {
    categoria: 'Café',
    emoji: '☕',
    items: [
      { tipo: 'Café instantáneo', producto: "Cruzeiro Clásico (lata/frasco/bolsa) 100-500g",      empresa: "Cruzeiro" },
      { tipo: 'Café instantáneo', producto: "Cruzeiro Suave 50/100/170/200g",                      empresa: "Cruzeiro" },
      { tipo: 'Café liofilizado', producto: "Cruzeiro Liofilizado 100% Arabica / Premium Intenso / varios formatos 50-200g", empresa: "Cruzeiro" },
      { tipo: 'Café grano molido', producto: "Cruzeiro Max Intensidad / Dark Roast / Altura 250g", empresa: "Cruzeiro" },
      { tipo: 'Café cappuccino', producto: "Cruzeiro Cappuccino Chocolate / Clásico / Caramelo Salado / Vainilla 120g", empresa: "Cruzeiro" },
      { tipo: 'Café descafeinado', producto: "Cruzeiro Descafeinado 170g",                          empresa: "Cruzeiro" },
      { tipo: 'Café en cápsula', producto: "Cruzeiro Espresso Cremoso 10un 56g",                    empresa: "Cruzeiro" },
    ],
  },
  {
    categoria: 'Semillas',
    emoji: '🌻',
    items: [
      { tipo: 'Maravilla', producto: "Mi Tierra Maravilla",                                  empresa: "Mi Tierra - NutrisaCorp" },
      { tipo: 'Linaza',    producto: "Mi Tierra Semilla de Linaza",                          empresa: "Mi Tierra - NutrisaCorp" },
      { tipo: 'Chía',      producto: "Mi Tierra Semilla de Chía",                            empresa: "Mi Tierra - NutrisaCorp" },
      { tipo: 'Sésamo',    producto: "Mi Tierra Sésamo Natural 100g / Tostado",              empresa: "Mi Tierra - NutrisaCorp" },
      { tipo: 'Zapallo',   producto: "NutrisaCorp Semilla de Zapallo",                        empresa: "NutrisaCorp" },
      { tipo: 'Quinoa',    producto: "Mi Tierra Semilla de Quinoa",                           empresa: "Mi Tierra - NutrisaCorp" },
    ],
  },
  {
    categoria: 'Pastas untables',
    emoji: '🥜',
    items: [
      { tipo: 'Hummus', producto: "Hummus Picante (Spicy) Red Spoon 260g",                   empresa: "Red Spoon (Elbelman)" },
      { tipo: 'Mantequilla maní', producto: "Creamy / Crunchy Peanut Butter American Classic 510g", empresa: "American Classic" },
      { tipo: 'Pasta pollo', producto: "La Preferida Pasta Pollo Ciboulette 125g",            empresa: "La Preferida" },
      { tipo: 'Pasta jamón', producto: "San Jorge Pasta de Jamón 125g",                       empresa: "San Jorge" },
    ],
  },
  {
    categoria: 'Productos congelados',
    emoji: '🧊',
    items: [
      { tipo: 'Verduras', producto: "Frutos del Maipo (Choclo Grano/Trozo / Arvejas / Habas / Porotos Granados / Mix Huerto / Primavera / Jardinera / Mix Rusa / Ajo Cubo / Porotos Verdes / Salteado Chapsui/Mediterráneo/Thai / Mix Tropical / Cebolla en Cubo/Morada / Mix Pimentón / Sofrito Tomate-Apio/Tradicional / Habas Peladas / Zapallo Cubo)", empresa: "Frutos del Maipo" },
      { tipo: 'Bases preparación', producto: "Frutos del Maipo (Base Arvejado / Carbonada / Estofado / Lentejas / Porotos Granados / Tomatican) 500g", empresa: "Frutos del Maipo" },
      { tipo: 'Verduras', producto: "San Jorge Arvejas / Choclo / Mix Primavera Poroto Verde 200g", empresa: "San Jorge" },
      { tipo: 'Fruta congelada', producto: "Frutos del Maipo Arándanos / Mango / Pulpa Maracuyá / Jugo Limón / Mix Berries", empresa: "Frutos del Maipo" },
      { tipo: 'Papas',    producto: "San Jorge Papas Prefritas/Duquesas 1kg / Frutos del Maipo Duquesas (BBQ/Tradicionales/Finas Hierbas) 500g/1kg / Prefritas/Cubo 500g/1kg", empresa: "San Jorge / Frutos del Maipo" },
      { tipo: 'Plato preparado', producto: "Frutos del Maipo Humitas Congeladas 600g",       empresa: "Frutos del Maipo" },
    ],
  },
  {
    categoria: 'Aceites',
    emoji: '🫒',
    items: [
      { tipo: 'Aceite oliva', producto: "Natura Oliva 500cc/1000cc",                          empresa: "Natura" },
      { tipo: 'Aceite vegetal', producto: "Natura Vegetal 900cc/3000cc",                       empresa: "Natura" },
      { tipo: 'Aceite maravilla', producto: "Natura Maravilla 500/900/1000/1500/3000/5000cc", empresa: "Natura" },
      { tipo: 'Aceite maravilla+oliva', producto: "Natura Maravilla con Oliva 900cc",          empresa: "Natura" },
    ],
  },
  {
    categoria: 'Alimentos de uso médico',
    emoji: '🏥',
    items: [
      { tipo: 'Nutrición enteral', producto: "Fresenius Kabi Diben (1.5 kcal hp/Neutro) / Frebini Original / Fresubin (2 kcal HP/HP Energy/Intensive/Original/Original Fibra) / Survimed OPD", empresa: "Fresenius Kabi" },
      { tipo: 'Suplemento oral', producto: "Fresenius Kabi Diben Drink / Fontactiv / Frebini Energy / Fresubin (2 kcal/Hepa/Jucy/Protein/Renal) / Supportan / Survimed / Thick & Easy / Glutamine Plus", empresa: "Fresenius Kabi" },
    ],
  },
  {
    categoria: 'Bebidas alcohólicas',
    emoji: '🍺',
    items: [
      { tipo: 'Cerveza', producto: "Jen Cranberry Menta / Original / Arándano Romero 330ml",   empresa: "Kufeo" },
    ],
  },
]

/** Helper: lista plana de todos los items con su categoría — útil para búsqueda */
export function todosLosItemsCeliacos(): Array<ItemCeliaco & { categoria: string }> {
  return CATALOGO_CELIACO_CONVIVIR.flatMap(c =>
    c.items.map(i => ({ ...i, categoria: c.categoria }))
  )
}

/** Helper: total de items en el catálogo */
export function totalItemsCeliacos(): number {
  return CATALOGO_CELIACO_CONVIVIR.reduce((acc, c) => acc + c.items.length, 0)
}
